name: Commit Message Linter

on:
  pull_request:

jobs:
  lint-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate commit messages
        run: |
          git log --format=%B -n 1 ${{ github.event.pull_request.head.sha }} | grep -E "^(fix|feat|chore|docs|style|refactor|test|perf): .{1,50}"
